### ISSUE TITLE
Projects & Sections CheckList

### ISSUE THREAD

**Issue by aliibsin** [aliibsin/Banana#3]
# Projects & Sections
## Functionality
- [ ] Icons for all current_user projects and New Project are available on '/home'
- [ ] Smooth, bug free navigation
### Upon clicking New Project icon
- [ ] Project create modal appears
- [ ] Allows user to create project upon valid form entries
- [ ] Errors should display if form entries are not valid
- [ ] Errors should clear if modal is closed for any reason
### Upon clicking a project icon
- [ ] Should be directed to project's show page
- [ ] Should display project name and description on header
- [ ] Should be able to edit project name and description by clicking on their respective text
- [ ] Should have working back (<) and delete (v) buttons
- [ ] Should display all of the project's sections
### Sections
- [ ] Should be able to create a new section by clicking the Add Section button
- [ ] Should be able to edit section name by clicking on its respective name text
- [ ] Error should display if section name is left blank
- [ ] Should be able to delete section by clicking the (x) to the left of the section name
### Additional functions
- [ ] All links after '/home/*' cannot be accessed unless user is logged in
- [ ] Should be able to refresh on any protected page and have all necessary values/entries populate correctly
## Style
- [ ] The site should look similar to actual site
- [ ] All relevant elements should have `cursor: pointer` on hover
- [ ] When errors are displayed, most elements should not move around the page (particularly input boxes)
- [ ] Remove Redux logger and all console.log()'s from production
## Seeds
- [ ] Adequate and appropriate seeds

**Comment by aliibsin** [comment]
Currently working on board view, and side bar. Afterwards, will start on tasks MVP. Will attempt to incorporate drag and drop after tasks.
